version: '2'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - 9090:80
    environment:
      WORDPRESS_DB_PASSWORD: flawless-sender!
      POSTMARK_PLUGIN_TESTING: POSTMARK_PLUGIN_TESTING
    volumes:
      - ./:/var/www/html/wp-content/plugins/postmark-plugin-development

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: flawless-sender!